# ejemplo instalación en local-----------------------------------------------
# devtools::install(file.path("d:", "R_Projects", "Scripts",
#                 "Github_packages","DataQualityDashboard-2.3.0"))
devtools::install(file.path("d:", "R_Projects", "Scripts",
                 "Github_packages","ParallelLogger-3.1.0"))

# Clean libraries------------------------------------------------------------
# paths = .libPaths()
#
# ## Try and detect bad files
# list.files(paths,
#            pattern = "^00LOCK*|*\\.rds$|*\\.RDS$",
#            full.names = TRUE)
#
# ## List files of size 0
# l = list.files(paths, full.names = TRUE)
# l[sapply(l, file.size) == 0]

# Cargar librerías-----------------------------------------------------------
library(AdhereR)
library(arsenal)
library(broom)
library(broom.mixed)
library(codebook)
# library(collapse)
library(cowplot)
library(data.table)
# library(DescTools)
library(DiagrammeR)
library(DiagrammeRsvg)
library(doParallel)
library(dotwhisker)
library(DT)
library(emojifont)
library(epiR)
library(extrafont)
library(fasttime)
library(foreach)
library(formattable)
library(future)
library(GGally)
library(ggfortify)
library(ggmap)
library(ggrepel)
library(ggpubr)
library(Gifi)
library(glue)
library(gmodels)
library(grid)
library(gridExtra)
library(gt)
library(haven)
library(httr)
# library(icdcoder)
library(incidence)
library(janitor)
library(jsonlite)
library(kableExtra)
library(labelled)
library(lubridate)
library(magrittr)
# library(maps)
library(maptools)
library(microbenchmark)
library(multidplyr)
library(naniar)
# library(plotly)
library(pointblank)
library(prettydoc)
library(profvis)
library(qwraps2)
library(r2rtf)
library(ragg)
library(R2WinBUGS)
library(RColorBrewer)
library(readr)
library(readxl)
library(rgdal)
library(rlang)
library(rlist)
# library(rms)
library(rsvg)
library(scales)
library(skimr)
library(smoothHR)
library(sp)
# library(spdep)
library(survival)
library(survminer)
library(stringi)
library(table1)
library(tictoc)
library(tidyfast)
library(tidylog)
library(tidymodels)
# library(tidyquant)
library(tidyverse)
library(tiff)
# library(tmap)
library(unglue)
library(wesanderson)
library(writexl)
library(zeallot)
